services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: ecommerce_laravel
    ports:
      - "3307:3306"
    volumes:
      - ./docker/data/db:/var/lib/mysql
